# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ffe6ddbea6b97d843be963e3a98c1842c12aa11276425edaf023af67bf19c0a6fc8ba1b84c679888ce5604f7d1b46259123be8bd4c580e06dca1a3bf112f76d

test:
  secret_key_base: 3f31ef4dd55b29fc68a68ab58167082bee4f0ca303ec1fd69053355562d03785de5e9411b7044a07cbd2b3edd22e372decbe638fc205b6492d2cfe838ab73227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
